-- MySQL Script generated by MySQL Workbench
-- Fri Nov  3 06:29:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MovieDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `MovieDB` ;

-- -----------------------------------------------------
-- Schema MovieDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MovieDB` DEFAULT CHARACTER SET utf8 ;
USE `MovieDB` ;

-- -----------------------------------------------------
-- Table `MovieDB`.`ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MovieDB`.`ratings` ;

CREATE TABLE IF NOT EXISTS `MovieDB`.`ratings` (
  `tconst` INT NOT NULL AUTO_INCREMENT,
  `average_rating` VARCHAR(45) NULL,
  `number_of_votes` INT NULL,
  PRIMARY KEY (`tconst`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MovieDB`.`title_basics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MovieDB`.`title_basics` ;

CREATE TABLE IF NOT EXISTS `MovieDB`.`title_basics` (
  `tconst` INT NOT NULL AUTO_INCREMENT,
  `primary_title` VARCHAR(45) NULL,
  `start_year` VARCHAR(45) NULL,
  `runtime` INT NULL,
  `ratings_tconst` INT NOT NULL,
  PRIMARY KEY (`tconst`, `ratings_tconst`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MovieDB`.`genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MovieDB`.`genres` ;

CREATE TABLE IF NOT EXISTS `MovieDB`.`genres` (
  `tconst` INT NOT NULL AUTO_INCREMENT,
  `genre_id` VARCHAR(45) NULL,
  PRIMARY KEY (`tconst`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MovieDB`.`title_basics_has_genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MovieDB`.`title_basics_has_genres` ;

CREATE TABLE IF NOT EXISTS `MovieDB`.`title_basics_has_genres` (
  `title_basics_tconst` INT NOT NULL,
  `title_basics_ratings_tconst` INT NOT NULL,
  `genres_genre_id` INT NOT NULL,
  PRIMARY KEY (`title_basics_tconst`, `title_basics_ratings_tconst`, `genres_genre_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
